/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/
var lsz = 530;

var Col0 = Array([lsz]);

Col0[0] = "url";

Col0[1] = "http://3RoundStones.com";

Col0[2] = "https://www.48factoring.com";

Col0[3] = "www.5psolutions.com";

Col0[4] = "abtassoc.com";

Col0[5] = "http://www.accela.com";

Col0[6] = "http://www.accenture.com/us-en/pages/index.aspx";

Col0[7] = "http://www.accuweather.com";

Col0[8] = "http://acxiom.com";

Col0[9] = "http://www.adaptive.com";

Col0[10] = "http://www.adobe.com/solutions/government.html";

Col0[11] = "http://www.myAidin.com";

Col0[12] = "www.alarm.com";

Col0[13] = "http://www.allianzusa.com";

Col0[14] = "http://www.allied.com";

Col0[15] = "http://www.allstate.com";

Col0[16] = "https://www.alltuition.com";

Col0[17] = "http://www.altova.com";

Col0[18] = "http://aws.amazon.com";

Col0[19] = "http://www.redball.com";

Col0[20] = "http://amida-tech.com/index.html";

Col0[21] = "http://www.analytica.net/";

Col0[22] = "apextechllc.com";

Col0[23] = "appallicious.com";

Col0[24] = "http://www.aquicore.com/";

Col0[25] = "http://archimedesmodel.com/";

Col0[26] = "http://www.areavibes.com/";

Col0[27] = "http://www.arpin.com";

Col0[28] = "http://home.downloadarrive.com";

Col0[29] = "http://www.asc-partners.com";

Col0[30] = "asset4.com";

Col0[31] = "http://www.atlasvanlines.com";

Col0[32] = "www.atsiteinc.com";

Col0[33] = "auntbertha.com";

Col0[34] = "http://www.aureus-sciences.com";

Col0[35] = "http://www.auto-grid.com";

Col0[36] = "http://www.avalara.com";

Col0[37] = "http://www.avvo.com";

Col0[38] = "http://www.ayasdi.com/";

Col0[39] = "azavea.com";

Col0[40] = "http://balefireglobal.com";

Col0[41] = "www.barchartmarketdata.com";

Col0[42] = "http://www.beinformed.com/BeInformed/website/en?init=true";

Col0[43] = "http://www.bekins.com";

Col0[44] = "https://mandasoft.com/";

Col0[45] = "http://www.berkshirehathaway.com";

Col0[46] = "http://betterlesson.com";

Col0[47] = "https://www.billguard.com";

Col0[48] = "http://www.bing.com";

Col0[49] = "http://accelrys.com";

Col0[50] = "http://bizvizz.com";

Col0[51] = "http://www.blackrock.com";

Col0[52] = "http://www.bloomberg.com";

Col0[53] = "http://www.boozallen.com";

Col0[54] = "http://www.bcg.com";

Col0[55] = "www.boundlessgeo.com";

Col0[56] = "http://www.bwater.com";

Col0[57] = "http://www.brightscope.com/";

Col0[58] = "http://www.buildfax.com/";

Col0[59] = "http://www.buildingeye.com";

Col0[60] = "www.buildzoom.com";

Col0[61] = "http://www.blr.com";

Col0[62] = "www.businessmonitor.com";

Col0[63] = "calcbench.com";

Col0[64] = "http://www.cig.com";

Col0[65] = "http://www.cambridgesemantics.com/home";

Col0[66] = "http://www.cancapital.com/";

Col0[67] = "http://www.canon.com";

Col0[68] = "http://www.capitalcube.com";

Col0[69] = "www.cappex.com";

Col0[70] = "captricity.com";

Col0[71] = "www.careset.com";

Col0[72] = "www.careset.com";

Col0[73] = "http://www.carfax.com";

Col0[74] = "http://www.caspio.com/";

Col0[75] = "http://www.castlebiosciences.com";

Col0[76] = "http://www.cbinsights.com/";

Col0[77] = "http://www.ceibasolutions.com";

Col0[78] = "www.opensecrets.org";

Col0[79] = "http://www.cerner.com";

Col0[80] = "http://www.certara.com";

Col0[81] = "http://www.cgi.com/en";

Col0[82] = "http://crai.com/";

Col0[83] = "https://www.schwab.com";

Col0[84] = "https://www.cas.org";

Col0[85] = "http://childcaredesk.com";

Col0[86] = "http://www.chubb.com";

Col0[87] = "http://www.citigroup.com/citi/";

Col0[88] = "www.CityScan.com";

Col0[89] = "http://www.citysourced.com/";

Col0[90] = "https://www.govtrack.us/civicimpulse";

Col0[91] = "http://civicinsight.com";

Col0[92] = "civinomics.com";

Col0[93] = "http://civisanalytics.com/";

Col0[94] = "http://www.cleanpowerfinance.com";

Col0[95] = "clearhealthcosts.com";

Col0[96] = "www.clearstorydata.com";

Col0[97] = "http://www.climate.com";

Col0[98] = "http://clinicast.net/";

Col0[99] = "http://cloudmade.com";

Col0[100] = "http://www.cloudspyre.com";

Col0[101] = "http://codeforamerica.org";

Col0[102] = "http://www.code-n.com";

Col0[103] = "www.collectiveip.com";

Col0[104] = "https://collegeabacus.org";

Col0[105] = "http://www.collegeboard.org";

Col0[106] = "comparedcare.com";

Col0[107] = "http://www.lifetechnologies.com/us/en/home/life-science/cancer-research/cancer-genomics/compendia-bioscience-life-technologies.html";

Col0[108] = "http://www.complianceandrisks.com";

Col0[109] = "http://www.computerpackages.com/";

Col0[110] = "http://conndot.com";

Col0[111] = "http://www.connectedu.com";

Col0[112] = "http://www.connotate.com";

Col0[113] = "www.constructionmonitor.com";

Col0[114] = "www.consumerreports.org";

Col0[115] = "http://coolclimate.berkeley.edu";

Col0[116] = "http://www.copyright.com";

Col0[117] = "http://www.corelogic.com";

Col0[118] = "http://www.costquest.com";

Col0[119] = "https://www.creditkarma.com";

Col0[120] = "creditsesame.com";

Col0[121] = "www.crowdanalytix.com";

Col0[122] = "https://www.dabohealth.com/#/";

Col0[123] = "http://www.datalogix.com";

Col0[124] = "http://datamade.us";

Col0[125] = "datamarket.com";

Col0[126] = "http://www.datamyne.com";

Col0[127] = "www.dataweave.com";

Col0[128] = "http://www.deloitte.com";

Col0[129] = "http://demystdata.com";

Col0[130] = "dobt.co";

Col0[131] = "developmentseed.org";

Col0[132] = "www.docketalarm.com";

Col0[133] = "http://www.dowjones.com";

Col0[134] = "http://www.dnb.com";

Col0[135] = "www.earthnetworks.com";

Col0[136] = "http://www.earth-observer.org/";

Col0[137] = "https://play.google.com/store/apps/details?id=com.joshclemm.android.quake&hl=en";

Col0[138] = "https://itunes.apple.com/us/app/eat-shop-sleep/id465262611";

Col0[139] = "https://www.ecodesk.com";

Col0[140] = "einstitutional.com";

Col0[141] = "http://letsembark.com";

Col0[142] = "http://www.emc.com/index.htm";

Col0[143] = "http://energypoints.com/";

Col0[144] = "energysolforum.com";

Col0[145] = "http://enervee.com";

Col0[146] = "enigma.io";

Col0[147] = "http://www.enscoplc.com/Home/default.aspx";

Col0[148] = "http://www.edrnet.com";

Col0[149] = "http://www.epsilon.com";

Col0[150] = "http://resources.alljobopenings.com/equality";

Col0[151] = "http://www.equifax.com/home/en_us";

Col0[152] = "http://www.equilar.com/";

Col0[153] = "http://www.ey.com";

Col0[154] = "http://www.escholar.com";

Col0[155] = "esri.com";

Col0[156] = "http://www.estately.com/";

Col0[157] = "http://www.everydayhealth.com";

Col0[158] = "http://www.evidera.com";

Col0[159] = "http://www.experian.com";

Col0[160] = "http://www.ehdp.com/";

Col0[161] = "https://exversion.com";

Col0[162] = "ez-xbrl.com";

Col0[163] = "http://www.factset.com";

Col0[164] = "http://www.factual.com";

Col0[165] = "http://www.farmers.com";

Col0[166] = "farmlogs.com";

Col0[167] = "fastcase.com";

Col0[168] = "https://www.fidelity.com";

Col0[169] = "http://www.findthebest.com";

Col0[170] = "http://firstfuel.com";

Col0[171] = "https://www.firstpointresources.com/";

Col0[172] = "https://www.fitchratings.com/web/en/dynamic/fitch-home.jsp";

Col0[173] = "http://www.flightaware.com/";

Col0[174] = "http://www.flightstats.com/";

Col0[175] = "http://www.flightview.com/";

Col0[176] = "http://www.foodtechconnect.com";

Col0[177] = "http://www.forrester.com";

Col0[178] = "https://foursquare.com";

Col0[179] = "http://www.fujitsu.com/us/";

Col0[180] = "https://www.fundingcircle.com";

Col0[181] = "https://www.futureadvisor.com";

Col0[182] = "www.fuzionapps.com";

Col0[183] = "http://www.gallup.com";

Col0[184] = "www.galorath.com";

Col0[185] = "http://www.garmin.com/en-US";

Col0[186] = "http://genability.com";

Col0[187] = "https://www.genospace.com";

Col0[188] = "http://geofeedia.com/";

Col0[189] = "http://www.geolytics.com";

Col0[190] = "www.geoscape.com";

Col0[191] = "https://getraised.com";

Col0[192] = "https://github.com";

Col0[193] = "http://www.glassymedia.com/";

Col0[194] = "http://www.goldenhelix.com/";

Col0[195] = "http://www.goodguide.com";

Col0[196] = "https://www.google.com/maps/about/explore/";

Col0[197] = "https://www.google.com/intl/en/about/";

Col0[198] = "http://www.ezgrantfiling.com";

Col0[199] = "http://www.govini.com";

Col0[200] = "govtribe.com";

Col0[201] = "fdazilla.com";

Col0[202] = "gradiant-research.com";

Col0[203] = "http://www.graebelmoving.com";

Col0[204] = "www.graematter.com";

Col0[205] = "http://www.granicus.com";

Col0[206] = "greatschools.org";

Col0[207] = "http://www.guidestar.org";

Col0[208] = "http://www.h3biomedicine.com";

Col0[209] = "www.harris.com";

Col0[210] = "http://hdscores.com";

Col0[211] = "HeadlightData.com";

Col0[212] = "http://www.healthgrades.com/";

Col0[213] = "http://www.healthline.com";

Col0[214] = "http://healthmap.org/";

Col0[215] = "http://www.healthpocket.com";

Col0[216] = "http://www.hellowallet.com/";

Col0[217] = "http://here.com";

Col0[218] = "https://www.honestbuildings.com";

Col0[219] = "https://www.hopstop.com/";

Col0[220] = "http://housefax.com/";

Col0[221] = "http://hmo.launchrock.com/";

Col0[222] = "www.ibm.com";

Col0[223] = "ideas42.org";

Col0[224] = "http://www.ifactorconsulting.com";

Col0[225] = "www.ificlaims.com";

Col0[226] = "http://imedicare.com";

Col0[227] = "http://www.aon.com/impactforecasting/impact-forecasting.jsp";

Col0[228] = "http://www.impaqint.com";

Col0[229] = "http://import.io";

Col0[230] = "http://www.imshealth.com/portal/site/imshealth";

Col0[231] = "http://incadence.com";

Col0[232] = "http://indoo.rs/";

Col0[233] = "http://infocommercegroup.com";

Col0[234] = "http://www.informatica.com";

Col0[235] = "http://www.innocentive.com";

Col0[236] = "http://www.innography.com";

Col0[237] = "http://www.innovestsystems.com";

Col0[238] = "http://www.inovalon.com/pages/default.aspx";

Col0[239] = "http://www.inrixtraffic.com";

Col0[240] = "http://corp.intelius.com/";

Col0[241] = "www.intermap.com";

Col0[242] = "www.investormill.com";

Col0[243] = "www.iodine.com";

Col0[244] = "iphix.net";

Col0[245] = "http://earth911.com/irecycle/";

Col0[246] = "itriagehealth.com";

Col0[247] = "http://auditanalytics.com/";

Col0[248] = "http://info.iwfinancial.com";

Col0[249] = "http://www.jjkeller.com";

Col0[250] = "http://www.jpmorganchase.com/corporate/Home/home.htm";

Col0[251] = "www.Junar.com";

Col0[252] = "http://junyo.com";

Col0[253] = "jurispect.com";

Col0[254] = "https://healthy.kaiserpermanente.org/html/kaiser/index.shtml";

Col0[255] = "www.karmadata.com";

Col0[256] = "www.keychainlogistics.com";

Col0[257] = "www.kidadmit.com";

Col0[258] = "kimonolabs.com";

Col0[259] = "http://www.msci.com/products/esg/#";

Col0[260] = "http://knoema.com/";

Col0[261] = "http://www.knowledgeagency.com/";

Col0[262] = "http://www.kpmg.com";

Col0[263] = "https://www.krollbondratings.com/";

Col0[264] = "http://kyruus.com";

Col0[265] = "lawdragon.com";

Col0[266] = "www.legalsciencepartners.net";

Col0[267] = "http://www.legcyte.com";

Col0[268] = "http://www.billtrack50.com/";

Col0[269] = "http://www.legistorm.com/";

Col0[270] = "https://www.lenddo.com/pages/what_is_lenddo/office";

Col0[271] = "https://www.lendingclub.com";

Col0[272] = "http://www.levelonetechnologies.com";

Col0[273] = "http://www.lexisnexis.com/en-us/home.page";

Col0[274] = "http://www.libertymutual.com";

Col0[275] = "https://openinnovation.lilly.com/dd/";

Col0[276] = "http://liquidr.com";

Col0[277] = "http://www.getlocavore.com";

Col0[278] = "www.logixdata.com";

Col0[279] = "http://www.loopnet.com";

Col0[280] = "www.loqate.com";

Col0[281] = "http://loseit.com";

Col0[282] = "www.makeloveland.com";

Col0[283] = "http://www.luciddesigngroup.com";

Col0[284] = "www.lumesis.com";

Col0[285] = "http://www.windowsphone.com/en-us/store/app/mango-transit/34083d75-dca6-4631-99be-4f9a3813dd73";

Col0[286] = "mapbox.com";

Col0[287] = "http://www.maponics.com/";

Col0[288] = "http://www.mapquest.com";

Col0[289] = "www.marinexplore.com";

Col0[290] = "http://www.marketsense.com/";

Col0[291] = "http://www.marlinllc.com";

Col0[292] = "http://www.marlinalter.com/";

Col0[293] = "http://www.mhfi.com";

Col0[294] = "http://www.mckinsey.com";

Col0[295] = "http://www.medwatcher.org";

Col0[296] = "http://www.mercaris.com/";

Col0[297] = "http://www.merrillcorp.com";

Col0[298] = "http://www.ml.com/index.asp?id=7695_15125";

Col0[299] = "https://www.metlife.com";

Col0[300] = "http://mhealthcoach.com";

Col0[301] = "http://www.microbilt.com/";

Col0[302] = "http://datamarket.azure.com";

Col0[303] = "https://www.mint.com";

Col0[304] = "https://www.moodys.com";

Col0[305] = "http://www.morganstanley.com";

Col0[306] = "http://www.morningstar.com";

Col0[307] = "http://www.mozio.com/";

Col0[308] = "https://www.muckrock.com";

Col0[309] = "www.munetrix.com";

Col0[310] = "http://www.municode.com";

Col0[311] = "http://www.nationalvanlines.com";

Col0[312] = "http://www.nationwide.com";

Col0[313] = "http://www.nautilytics.com";

Col0[314] = "www.navico.com";

Col0[315] = "http://www.nera.com/";

Col0[316] = "http://www.nerdwallet.com";

Col0[317] = "http://mommaps.com/";

Col0[318] = "http://www.nextstepliving.com";

Col0[319] = "http://www.nextbus.com";

Col0[320] = "ngap.com";

Col0[321] = "http://www.nielsen.com/us/en.html";

Col0[322] = "https://www.noesisenergy.com/site/";

Col0[323] = "https://www.nonprofitmetrics.com";

Col0[324] = "http://northamericanvanlines.com";

Col0[325] = "www.noveda.com";

Col0[326] = "http://www.nucivic.com";

Col0[327] = "http://numedii.com";

Col0[328] = "http://www.oliverwyman.com/index.html";

Col0[329] = "www.ondeck.com";

Col0[330] = "https://www.onstar.com/web/portal/home?g=1";

Col0[331] = "ontodia.com";

Col0[332] = "http://www.onvia.com";

Col0[333] = "www.opendatanation.com";

Col0[334] = "http://opencounter.us";

Col0[335] = "http://opengov.com";

Col0[336] = "http://openplans.org";

Col0[337] = "opportunityspace.org";

Col0[338] = "http://www.optensity.com";

Col0[339] = "optigov.com";

Col0[340] = "http://www.optuminsight.com";

Col0[341] = "http://www.orlinresearch.com";

Col0[342] = "http://www.osisoft.com";

Col0[343] = "http://www.otcmarkets.com/home";

Col0[344] = "http://outline.com";

Col0[345] = "http://www.oversightsystems.com";

Col0[346] = "http://www.overturecorp.com/";

Col0[347] = "owler.com";

Col0[348] = "https://www.palantir.com";

Col0[349] = "www.panjiva.com";

Col0[350] = "www.pbworld.com";

Col0[351] = "www.patentlyo.com";

Col0[352] = "http://www.patientslikeme.com";

Col0[353] = "http://www.pave.com";

Col0[354] = "www.paxata.com";

Col0[355] = "http://www.payscale.com";

Col0[356] = "https://peerj.com";

Col0[357] = "http://www.peoplepowerco.com/";

Col0[358] = "http://www.persint.com/";

Col0[359] = "http://personaldemocracy.com";

Col0[360] = "personal.com";

Col0[361] = "http://www.personalis.com";

Col0[362] = "www.corporate.petersons.com";

Col0[363] = "http://www.pev4me.com";

Col0[364] = "www.pixia.com";

Col0[365] = "www.placeilive.com";

Col0[366] = "http://planetecosystems.com";

Col0[367] = "https://plotwatt.com";

Col0[368] = "https://www.unigo.com/from-plusu.aspx";

Col0[369] = "policymap.com";

Col0[370] = "http://www.politify.us";

Col0[371] = "http://poncho.is/";

Col0[372] = "popvox.com";

Col0[373] = "porch.com";

Col0[374] = "http://www.possibilityu.com/";

Col0[375] = "http://www.poweradvocate.com/index.html";

Col0[376] = "http://www.practicefusion.com";

Col0[377] = "http://www.predilytics.com";

Col0[378] = "http://www.pwc.com/us/en/index.jhtml";

Col0[379] = "http://www.programmableweb.com";

Col0[380] = "http://www.progressive.com";

Col0[381] = "http://propellerhealth.com";

Col0[382] = "http://www.propublica.org/";

Col0[383] = "http://www.publicengines.com/";

Col0[384] = "www.pyaanalytics.com";

Col0[385] = "www.qadoenergy.com";

Col0[386] = "http://www.quandl.com";

Col0[387] = "quertle.com";

Col0[388] = "http://quid.com";

Col0[389] = "http://www.rrdonnelley.com";

Col0[390] = "http://www.rand.org";

Col0[391] = "http://www.randmcnally.com/";

Col0[392] = "http://rankandfiled.com/";

Col0[393] = "http://goranku.com";

Col0[394] = "www.rapidcyclesolutions.com";

Col0[395] = "http://www.realtor.com/";

Col0[396] = "http://www.recargo.com";

Col0[397] = "https://www.recipal.com/";

Col0[398] = "http://www.redfin.com";

Col0[399] = "http://redlaser.com";

Col0[400] = "http://www.reedelsevier.com/Pages/Home.aspx";

Col0[401] = "www.reisystems.com";

Col0[402] = "https://www.relsci.com";

Col0[403] = "www.remi.com";

Col0[404] = "http://www.retroficiency.com";

Col0[405] = "https://revaluate.com/";

Col0[406] = "http://www.revelstonelabs.com";

Col0[407] = "http://www.rezolvegroup.com";

Col0[408] = "http://rivetsoftware.com";

Col0[409] = "www.roadify.com";

Col0[410] = "http://www.robinsonyu.com";

Col0[411] = "http://www.russell.com/indexes/";

Col0[412] = "http://sagebase.org";

Col0[413] = "http://www.sap.com/";

Col0[414] = "http://www.sas.com/";

Col0[415] = "http://www.scaleunlimited.com/";

Col0[416] = "scienceexchange.com";

Col0[417] = "www.seabourneinc.com";

Col0[418] = "en.seeclickfix.com";

Col0[419] = "https://www.sigfig.com/";

Col0[420] = "http://simpleenergy.com";

Col0[421] = "http://www.simpletuition.com/";

Col0[422] = "http://www.slashdb.com/";

Col0[423] = "http://smartusys.com/";

Col0[424] = "smartasset.com";

Col0[425] = "http://smartprocure.us/";

Col0[426] = "http://smartronix.com/";

Col0[427] = "www.snapsense.co";

Col0[428] = "http://www.socialexplorer.com/";

Col0[429] = "http://socialhealthinsights.com/";

Col0[430] = "http://socialeffort.co/";

Col0[431] = "www.socrata.com";

Col0[432] = "http://www.solarcensus.com";

Col0[433] = "solarlist.com";

Col0[434] = "http://www.sophicalliance.com";

Col0[435] = "https://www.capitaliq.com";

Col0[436] = "www.spacecurve.com";

Col0[437] = "http://www.spesohealth.com/";

Col0[438] = "http://www.spikescavell.com/";

Col0[439] = "http://www.splunk.com/";

Col0[440] = "http://www.spokeo.com/";

Col0[441] = "www.spotcrime.com";

Col0[442] = "http://spothero.com/";

Col0[443] = "http://stamen.com/";

Col0[444] = "http://www.standardandpoors.com/en_US/web/guest/home";

Col0[445] = "http://www.statefarm.com/";

Col0[446] = "http://www.sterlinginfosystems.com/";

Col0[447] = "http://www.stevensworldwide.com/";

Col0[448] = "http://www.stillwater-sc.com";

Col0[449] = "http://www.stocksmart.com";

Col0[450] = "http://stormpulse.com/";

Col0[451] = "http://www.streamlinksoftware.com/";

Col0[452] = "streetcredsoftware.com";

Col0[453] = "http://streeteasy.com/";

Col0[454] = "http://www.suddath.com/";

Col0[455] = "http://www.symcat.com/";

Col0[456] = "http://www.synthicity.com/";

Col0[457] = "http://www.troweprice.com";

Col0[458] = "http://www.tableausoftware.com/";

Col0[459] = "tagnifi.com";

Col0[460] = "http://www.telenav.com/";

Col0[461] = "http://www.tendrilinc.com/";

Col0[462] = "http://www.teradata.com/";

Col0[463] = "http://www.advisory.com/";

Col0[464] = "http://www.bridgespan.org/";

Col0[465] = "http://docgraph.org/";

Col0[466] = "www.govtechfund.com";

Col0[467] = "schorkreport.com";

Col0[468] = "http://www.vanguard.com/";

Col0[469] = "thinkcomputer.com";

Col0[470] = "http://www.thinknum.com/";

Col0[471] = "http://thomsonreuters.com/";

Col0[472] = "http://www.topcoder.com/";

Col0[473] = "http://intelligence.towerdata.com/";

Col0[474] = "http://www.TransparaGov.com/";

Col0[475] = "http://www.transunion.com/";

Col0[476] = "http://www.citeline.com/products/trialtrove/";

Col0[477] = "http://trialx.com/";

Col0[478] = "http://www.trintech.com/";

Col0[479] = "http://www.truecar.com/";

Col0[480] = "trulia.com";

Col0[481] = "https://www.trustedid.com/";

Col0[482] = "https://www.tuvalabs.com/";

Col0[483] = "https://www.uber.com/";

Col0[484] = "www.unigo.com";

Col0[485] = "http://www.unitedmayflower.com/";

Col0[486] = "http://urbanairship.com/";

Col0[487] = "http://www.urbanmapping.com/";

Col0[488] = "http://www.usgreendata.com/";

Col0[489] = "http://www.usnews.com/";

Col0[490] = "https://www.usaa.com";

Col0[491] = "http://www.ussearch.com/";

Col0[492] = "www.verdafero.com";

Col0[493] = "www.vimo.com";

Col0[494] = "www.visualdod.com";

Col0[495] = "niinja.co";

Col0[496] = "https://www.vitalchek.com/";

Col0[497] = "http://www.vitals.com/";

Col0[498] = "vizzuality.com";

Col0[499] = "www.votizen.com";

Col0[500] = "www.walkscore.com";

Col0[501] = "http://www.watersmartsoftware.com/";

Col0[502] = "http://www.wattzon.com/";

Col0[503] = "http://waybetterpatents.com/";

Col0[504] = "http://www.weather.com/";

Col0[505] = "http://www.wdtinc.com/";

Col0[506] = "http://www.wunderground.com/";

Col0[507] = "https://www.webfilings.com/";

Col0[508] = "webitects.com";

Col0[509] = "http://www.webmd.com/";

Col0[510] = "http://www.weightwatchers.com/";

Col0[511] = "http://wemakeitsafer.com/";

Col0[512] = "http://www.wheatonworldwide.com/";

Col0[513] = "http://www.whitbygroup.com";

Col0[514] = "http://www.wolfram.com/";

Col0[515] = "http://www.wolterskluwer.com/";

Col0[516] = "https://www.workhands.us/";

Col0[517] = "http://www.xatori.com/";

Col0[518] = "xcential.com";

Col0[519] = "http://www.xdayta.com";

Col0[520] = "http://www.xignite.com/";

Col0[521] = "http://www.yahoo.com/";

Col0[522] = "www.zebucompliance.com";

Col0[523] = "http://www.yelp.com/";

Col0[524] = "http://www.yourmapper.com";

Col0[525] = "http://www.zillow.com/";

Col0[526] = "http://www.zocdoc.com/";

Col0[527] = "http://www.zonability.com/";

Col0[528] = "www.Zonerapp.com";

Col0[529] = "http://www.zurichna.com/";

url = "";

intercept = -2.5194422395886593;
stat = [];
coef = [-0.074779205, 0.545172349, -2.42E-6] //0.003514723, -0.317395595, -0.19396821, -0.000638795, 0.013969635, 0.053140112, 0.013969635, 0.011924084];

Color = {
    CRIMSON: 'crimson',
    ORANGERED: 'orangered',
    ORANGE: 'orange',
    YELLOW: 'yellow',
    LIGHTGREEN: 'lightgreen',
    GREEN: 'green'
}

sigmoid = function() {
	var sum = 0.0;
	for (var i = 0, length=stat.length-1; i < length; i++) { //Sum of coefs*vals
		sum += coef[i]*(stat[i]-intercept);
	}
	sum *= -1.0;
	sum = 1.0+(Math.pow(Math.E, sum));
	return Math.round(1.0/sum);

}

getSiteData = function() {
	chrome.storage.local.get(null, function(items) {
    	var keyList = Object.keys(items);
    	stat[0] = keyList[0];
    	stat[1] = keyList[1];
    	stat[2] = keyList[2];
	});
};


	// stat[0] = 16//Math.floor(Math.random()*((249)+1))+16; //URL_LENGTH
	// stat[1] = 7//Math.floor(Math.random()*((43)+1))+5; //#_OF_SPECIAL_CHAR
	// stat[2] = 263//Math.floor(Math.random()*((649263)+1))+0; //HTTP_HEADER_SIZE
	// stat[3] = 7//Math.floor(Math.random()*((1194)+1))+0; //#_OF_TCP_PACKET
	// stat[4] = 0//Math.floor(Math.random()*((708)+1))+0; //#_OF_TCP_PORT
	// stat[5] = 2//Math.floor(Math.random()*((17)+1))+0; //#_OF_IP
	// stat[6] = 700//Math.floor(Math.random()*((2362906)+1))+0; //BYTES_TRASNFERRED
	// stat[7] = 9//Math.floor(Math.random()*((1198)+1))+0; //SOURCE_PACKETS
	// stat[8] = 10//Math.floor(Math.random()*((1284)+1))+0; //REMOTE_PACKETS
	// stat[9] = 1153//Math.floor(Math.random()*((1198)+1))+0; //APP_PACKETS
	// stat[10] = 2//Math.floor(Math.random()*((20)+1))+0; //QUERY_TIME

	// stat[0] = Math.floor(Math.random()*((249)+1))+16; //URL_LENGTH
	// stat[1] = Math.floor(Math.random()*((43)+1))+5; //#_OF_SPECIAL_CHAR
	// stat[2] = Math.floor(Math.random()*((649263)+1))+0; //HTTP_HEADER_SIZE
	// stat[3] = Math.floor(Math.random()*((1194)+1))+0; //#_OF_TCP_PACKET
	// stat[4] = Math.floor(Math.random()*((708)+1))+0; //#_OF_TCP_PORT
	// stat[5] = Math.floor(Math.random()*((17)+1))+0; //#_OF_IP
	// stat[6] = Math.floor(Math.random()*((2362906)+1))+0; //BYTES_TRASNFERRED
	// stat[7] = Math.floor(Math.random()*((1198)+1))+0; //SOURCE_PACKETS
	// stat[8] = Math.floor(Math.random()*((1284)+1))+0; //REMOTE_PACKETS
	// stat[9] = Math.floor(Math.random()*((1198)+1))+0; //APP_PACKETS
	// stat[10] = Math.floor(Math.random()*((20)+1))+0; //QUERY_TIME

getColor = function(score) {
	if (score >= 93)
		return Color.GREEN;
	else if (score >= 85)
		return Color.LIGHTGREEN;
	else if (score >= 79)
		return Color.YELLOW;
	else if (score >= 73)
		return Color.ORANGE;
	else if (score >= 55)
		return Color.ORANGERED;
	return Color.CRIMSON;
};

window.onload = function() {
	document.querySelector('#scan').addEventListener('click', e => {
		chrome.tabs.executeScript(null,{file:"scripts/highlight.js"});
		getSiteData();
		var sec = (100.0*sigmoid());
		var pri = Math.floor(Math.random()*(101));
		var ss = sec.toString();
		var ps = pri.toString();
		document.getElementById('security').style.backgroundColor = getColor(sec);
		document.getElementById('security').innerHTML = "<br>"+ss+"</br>";
		document.getElementById('privacy').style.backgroundColor = getColor(pri);
		document.getElementById('privacy').innerHTML = "<br>"+ps+"</br>";
		
	});
}